version: "2"
services:
  rb_portal_production:
    restart: always
    image: 024847829446.dkr.ecr.eu-west-1.amazonaws.com/cirrusconnect/rb-portal:production
    environment:
      - VIRTUAL_HOST=live.rb.cirrus-connect.com
    networks:
      - web
networks:
  web:
    external:
      name: dockerizedbase_web